name: Development workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test-checkout:
    runs-on: windows-latest
    steps:
    - name: Check out repository code 
      uses: actions/checkout@v4
      with:
        path: main
   
    - name: Check out repository code 2
      uses: actions/checkout@v4
      with:
        repository: lucasAntunesTam/CICD_Pipeline
        path: main2
      
    - name: Build nuget package 
      shell:  pwsh
      run: |
        ls ${{ github.workspace }}\main
        ls ${{ github.workspace }}\main2

    - name: Call reusable workflow 
      uses:  lucasAntunesTam/CICD_Pipeline/.github/workflows/ReusableWorkflow.yml@main
      with:
        test: ${{ github.workspace }}
